### ISSUE TITLE
Tag from master or develop branch

### ISSUE THREAD

**Issue by tomusborne** [helen/action-wordpress-plugin-deploy#41]
This might be a silly question, but I'm setting this up for the first time and want to make sure I'm doing it right.

Let's say I'm developing a new version in a `release/2.0` branch.

When my new version is ready, should I:

a) Merge `release/2.0` with `master`, and tag a new version from `master`
b) Tag a new version from my `release/2.0` branch, and then merge with `master` once the 

I have the assets action set up as well, so I'm trying to figure out which way is preferable without causing conflicts.

Thanks!

**Comment by helen** [comment]
Hi @tomusborne! I have not tried tagging off of another branch for .org release purposes but it shouldn't really matter to the Action because of the way Git tags work, it's more a question of what you want your history and tags to look like. The assets one is pickier because it won't run if you have any non-asset changes when comparing the branch (and any build process) with the SVN repo contents, so for that you'd want to merge changes into `master` before merging that back into your release branch.

**Comment by helen** [comment]
Of course, if you run into problems with whichever method you choose, let us know!

**Comment by tomusborne** [comment]
Thanks for getting back to me so quickly @helen!

Got it, so I can merge into `master`, and the asset build will fail because of all the non-asset/readme changes.

Then I can tag a release and it will deploy to wp.org along with the updated readme.

Makes sense, thanks again!

**Comment by helen** [comment]
Yup! It's kind of annoying that you get a failure, there used to be a neutral exit state but the last I checked it hadn't been brought back yet. But, if you expect the failure, then it's all good!
