### ISSUE TITLE
Binary Permission issue

### ISSUE THREAD

**Issue by padams** [helen/action-wordpress-plugin-deploy#49]
**Describe your question**

My plugin uses composer to download tar package from a custom repository. The unpacked tar contains a binary that has executable permission set on the filesystem.

When I run `composer install` locally all is well.

When i run `composer install` as an action workflow step right before the `10up/action-wordpress-plugin-deploy` step, the executable permission on the binary file does not get reflected in SVN. I believe this is becuase I need to run `svn propset` on the file to tell SVN that it's an executable.

Any ideas about the best way add this ot the workflow? Is there a hook into the action's SVN process that I'm not seeing maybe something similar to a `.distignore` file?

**Comment by helen** [comment]
Apologies for having neglected this repo for a bit - that is interesting! I don't really have any good ideas here, it feels slightly dangerous to just run commands semi-arbitrarily from a text file or something like that but I'm not sure how else you'd inject into the middle of the action. I wonder why it works locally for you? I would have thought a propset issue would happen either way, would be good to know for sure what the issue is so we can fix appropriately.

**Comment by jeffpaul** [comment]
@padams are you able to help triage this a bit further so we can work on an appropriate fix?

**Comment by jeffpaul** [comment]
Closing this due to no response from @padams, but please feel free to re-open if additional information can be shared... thanks!
