### ISSUE TITLE
Push to svn on release only (not pre-release)

### ISSUE THREAD

**Issue by KevinBatdorf** [helen/action-wordpress-plugin-deploy#50]
Similar to  https://github.com/10up/action-wordpress-plugin-deploy/issues/5, I would like a workflow where I could tag a pre-release, run the build (including zip file), but _not_ deploy to the svn. 

The intent is to have a final round of testing with the build artifact before an actual release.

It looks like this would involve rewriting the `.distignore` workflow to run more like the `.gitattributes`, and generate the zip file from `$TMP_DIR` instead of the svn directly. 

Does this seems like something useful? I'm not even sure it's doable, to be fair, as I'm just using Github actions now for the first time!

**Comment by helen** [comment]
Hi there - is this still an issue for you? It sounds like you want to run a workflow without this action at all, in which case there isn't anything to do here in this repository. Things like the build and ZIP generation can all be done directly as commands on the runner in a workflow, this action just happens to handle the ZIP part as a part of the process because of the SVN component, but if you're not dealing with that then you don't need this action at all.

**Comment by KevinBatdorf** [comment]
I wanted it to ideally not trigger on pre-release (which is a checkbox that shows when making a release). All good though, this issue was opened over a year ago so I just stopped using the pre-release feature

**Comment by helen** [comment]
I see, to get it to not run you'd want to change the trigger in your workflow file, I think it's instead of `published` you use `released`, and then a separate one for the `prereleased` event that runs build and creates a ZIP as the workflow steps. I hope that makes sense - you're looking for things that are managed by the GitHub part, not this particular action.

**Comment by KevinBatdorf** [comment]
Thanks for following up. Just looked it up in the docs and it looks like there are "activity types" that you would target on the release event. That makes sense.

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

Possibly going to be adding this workflow to a few projects in the coming weeks so I'll test it out and see if there are any issues. Thanks
