### ISSUE TITLE
Help With composer

### ISSUE THREAD

**Issue by luizkim** [helen/action-wordpress-plugin-deploy#54]
The project I use needs to send the vendor folder that is generated by the composer to Wordpress's SVN.

I run the composer install according to your read.me, but apparently it does this before creating the SVN folder and therefore the files are not uploaded.

Here is the link to my configuration file:
https://github.com/Frete-Click/WooCommerce/blob/master/.github/workflows/wordpress-svn-deploy.yml

**Comment by Preciousomonze** [comment]
@luizkim 
I am seeing your vendor folder being added
👇🏼
![Screenshot 2020-09-19 at 02 21 35](https://user-images.githubusercontent.com/15174834/93655986-f4213000-fa1e-11ea-893f-219864266c03.png)

**Comment by luizkim** [comment]
This is another process where you try to lower the vendor, but it did not go. I had to add the vendor folder inside the project on GITHUB (which is not recommended)

**Comment by Preciousomonze** [comment]
From what I am seeing, you do not have a .wordpress-org folder
And .distignore folder
Maybe that might be the issue.😅

**Comment by luizkim** [comment]
You did not understand.

I uploaded the files to GITHUB precisely because today the action does not do what I need.

It needs to go up to wordpress, but it cannot be in the GITHUB repository (today it is in the repository because I have no alternative).

**Comment by dingo-d** [comment]
Hi!

The same thing happens to me, not sure what I'm doing wrong 

https://github.com/dingo-d/woo-solo-api/blob/develop/.github/workflows/deploy.yaml

The `php-actions/composer@v4` action should install the packages that are needed for prod release, but when I use it

```yaml
            - uses: php-actions/composer@v4
              with:
                dev: no
                php_version: 7.3
                composer_version: 1
```

I don't get the vendor file inside my tag on wordpress.org. I'm using autoloading so I need it there.

**Comment by nextgenthemes** [comment]
Was anyone able to solve this? Is it just the `/vendor` dir or anything you create after the checkout?

I am running into this shit mysefl now. `/vendor` is in `.gitignore` as it's supposed to be but NOT in `.gitattributes` with `export-ignore`. Or that other exclusion file this thing uses. Thankfully I prepared my code for this to happen as I saw this b4 I tried myself. Intuition I guess.

The maintainers do not seem to care, this is pretty common use case. It's not recommended having composer deps checked into git. Not sure if it would work than, but I guess I have to try this now.

**Comment by helen** [comment]
@nextgenthemes I don't really know what you're hoping for with that kind of comment. I, along with my team, have been extremely busy for the last 6 months with major back-to-back projects and some support requests have slipped through the cracks. This one in particular is [specifically addressed in the README](https://github.com/10up/action-wordpress-plugin-deploy#excluding-files-from-deployment).

We use this action for plugins that include built files, both via Composer and npm-based builds. That is the reason there is the "other exclusion file this thing uses". Using `.distignore` bypasses `git archive` (which respects **both** `.gitignore` and `.gitattributes`), and includes any files in the workspace (unless ignored by `.distignore`) even if they are not committed. It is less than ideal to have this kind of confusing split just based on the presence of a `.distignore` file, but it was the cleanest way to solve for built plugins without introducing additional configuration that is unnecessary for the majority.

**Comment by nextgenthemes** [comment]
@helen Sorry I made a mistake not reading the readme again, thinking this is not possible **because this issue was:**

1. Still open.
1. Not solved by anyone here.

And what I hoped is exactly what happened ;) Seems contrary to your point but ~4 people had this issue and did not seem to come to the conclusion themselves and no answer from you. Saw anther open issue with someone not reading or able to get the readme apparently. They all wanted to get an answer, I did get one. So thanks.

I just read the readme again and its pretty hard to understand if you fly over it. I am not familiar with `.distignore` at all and thought it was yet another way to exclude files (it is) but missed that is disables the `git archive`. The readme on that could probably be improved and have a straight forward, straight to the point. "If you need `vendor` do this ...". 

I personally do not like to learn and mess with yet another thing and have `.gitignore/attri` already setup, so I actually like how `git archive` is used. Just the thought of using yet another thing does not feel good for me. I think something like this
```yaml
      with:
        generate-zip: false
        extra-folders:
          - vendor
          - dist
          - foobar
```
... would be great, so it still uses the normal `git archive` process but just copies over specific folders from working dir over when asked. I do not know the point of `.distignore` and why WP-CLI this, so I am not going to claim this is would better/cleaner just what I have in mind.

So for anyone interested in my specific case I just went with a custom `php/Admin/vendor` for that tiny package without deps. This way I do not accidentally commit `./vendor` with possibly a lot of dev stuff in there. So I am going the "bad practice" way to actually including this tiny composer dep in git. But I fear I have to revisit this later. But for now I not have to change anything.

This is how you can install in a custom folder without actually changing the config.
```
COMPOSER_VENDOR_DIR=php/Admin/vendor composer --no-dev update
```

**Comment by helen** [comment]
"I don't know what .distignore is so I want git archive to do something it explicitly is not designed to do instead" is not a good reason to be disrespectful or engage in development practices that may present difficulties later. If you have a build process involving uncommitted files, you should use a .distignore file.
