### ISSUE TITLE
Specify scope for GITHUB_TOKEN

### ISSUE THREAD

**Issue by marijnbent** [helen/action-wordpress-plugin-deploy#62]
**Is your enhancement related to a problem? Please describe.**
To improve the docs, it would be nice which scopes the token is required to have

**Describe the solution you'd like**
A list of scopes required for the personal access token.

**Context**
Available options:
<img width="769" alt="Screenshot 2021-01-14 at 10 43 32" src="https://user-images.githubusercontent.com/11903095/104573618-61537380-5655-11eb-8564-f89b3d7cd65e.png">

**Comment by marijnbent** [comment]
When trying to create a GITHUB_TOKEN secret, I get the message this name is not allowed. Is it correct that you should not set this value @helen?

**Comment by jeffpaul** [comment]
@marijnbent its been a bit since I've had to set this up from scratch, but I don't believe you need to create a Personal Access Token and GITHUB_TOKEN doesn't need to be set up / configured.  As long as you've configured:
- build steps for your plugin
- SVN password + username as org/repo secrets
- SLUG param if yours is different than the repo name
- ASSETS_DIR if yours aren't in `.wordpress-org`
- .distignore / .gitattributes for files to skip on deploy

Setting up ^ those items _should_ be all that's needed.  Let us know if you've done that and are NOT seeing the action deploy properly.

**Comment by marijnbent** [comment]
Thanks for your reply Jeff! I tried to run 'Upload release asset' on an 'add tag' action. This combination doesn't seem to work (probably because no release exists?). The deploy on a published release works perfectly, without the need to create a GitHub token.

**Comment by jeffpaul** [comment]
@marijnbent note that I proposed an update to our docs in #63, let me know if that seems to help better call out requirements related to what you were trying to do... thanks!

**Comment by marijnbent** [comment]
Perfect Jeff! Congrats on the whitehouse.gov site btw 🤓
