### ISSUE TITLE
Use Without SVN Deployment

### ISSUE THREAD

**Issue by dcooney** [helen/action-wordpress-plugin-deploy#66]
**Describe your question**
👋🏻  Is it possible to use this action without an SVN deployment? The `.distignore`, `npm build` and `.zip` attachment to a release is perfect for some non .org plugins of mine, but I don't need the SVN aspect.

Is that possible?

**Comment by helen** [comment]
Hello! For a workflow like that you should be able to run most of those steps directly as commands on the runner. This Action is specifically to ease over the SVN barrier; while the ZIP file is generated in the Action due to the way it copies into other directories you can see the actual attachment actually happens with a different Action in the example workflow file, and `npm build` is itself a direct command and not related to this Action. I imagine your workflow file would need to do something like checkout, run the build, create a ZIP that respects whatever ignore/exclude file (I am not clear on whether `zip` accepts the same exclude patterns as `rsync`, which is what the `.distignore` is for), and then attach said ZIP to a release. So instead of referencing this Action in a step, that step would just directly run `zip` instead. You may need to experiment or research a bit to make sure the paths are correct but I think everything just executes in the workspace directory by default.

**Comment by dcooney** [comment]
Thank you @helen, appreciate the detailed response.
