### ISSUE TITLE
Delete old tags from SVN

### ISSUE THREAD

**Issue by AlecRust** [helen/action-wordpress-plugin-deploy#70]
**Is your enhancement related to a problem? Please describe.**

I have pushed many tags to SVN, but the [recommendation](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#delete-old-versions) is to delete old tags.

People may want to limit the number of tags in the SVN repository to say the last 5 releases, as making releases older than this available to download may cause side effects.

**Describe the solution you'd like**

Removing specified tags or restricting the number of tags in the SVN repository could be a feature of this action?

**Comment by jeffpaul** [comment]
@AlecRust the Plugin Handbook does not seem to make that a recommendation so much as point out its an option that does not have any listed positive effect:
> Since SVN is a release repository, many developers chose to remove older (non-supported) versions of their plugins. As of 2019, this no longer speeds up releases, as the build process only addresses tags with changed files.

The easiest path to handling this, if its desired, is probably directly in SVN itself.  For example: https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-rename.html.

**Comment by AlecRust** [comment]
[This](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#how-many-old-releases-should-i-keep-in-svn) is probably a better reference:

> **How many old releases should I keep in SVN?**
> 
> As few as possible. Very rarely does anyone need your old code in the release repository. Remember, SVN is not meant for your code versioning. You can use Github for stuff like that. SVN should have your current release versions, but you don’t need all the minor releases to all the previous versions. Just the last one or two for them is good.

WordPress also [recommends](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#how-many-versions-should-i-keep-in-my-changelog) only including the most recent couple major versions in your `readme.txt` changelog:

> **How many versions should I keep in my changelog?**
> 
> Always keep the current major release in your change log. For example, if your current version is 3.9.1, you’ll want that and 3.9 in the change log. Older versions should be removed and migrated to a changelog.txt file. That will allow them to be accessible to users, while keeping your readme shorter and more pertinent. At most, keep the most recent version of your plugin and one major version back in your readme’s changelog.

So it seems logical to keep the same tags in SVN that you also have listed in the changelog. No doubt I can do this manually, but I'm looking to automate it.

**Comment by jeffpaul** [comment]
@AlecRust I'm not immediately sure how this action would handle this.  What would be your expected workflow?

**Comment by AlecRust** [comment]
In order to comply with the changelog recommendations I'm restricting my changelog to only include the range between the two most recent major versions.

I suppose since this action performs the interaction with the SVN repository I was thinking it could have a `keep-last-releases` option where you specified the number of tags to keep in the SVN repository

Or, a `keep-tags-since` option where you specified a tag name and tags before that version were deleted from the SVN repository.

**Comment by helen** [comment]
Hello! I'd like to keep this action tightly focused on deployment; what you're describing is something I would frame as more of a clean up or maintenance type of task. Whether doing this is necessary or not, I'll refrain from opining, but IMO best practice as far as CI goes would be to run that as a separate step in your workflow so it is separated from the deployment (e.g. if deployment otherwise succeeds you don't want it to show a failure of deployment). I see two potential paths forward if you're hoping for a workflow to manage this for you:
* Add a step that directly runs the deletion commands for you (SVN [is available on their Ubuntu runners](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md))
* Create an Action that does the deletion, likely based on passed args, and then reference that in a new step in your workflow file
